### ISSUE TITLE
Error message when I am trying to build VALERA

### ISSUE THREAD

**Issue by ldf92** [frankhuhu/valera#1]
Hi,

I am trying to build VALERA based on the instruction on your website(http://spruce.cs.ucr.edu/valera/). However, I constantly see error messages as shown below. It happens after I add manifest file in ".repo/local_manifests/local_manifest.xml" and perform "repo sync" command. Do you know why such error message occur?

Fetching project platform/external/bsdiff
Exception in thread Thread-211:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/ase/valera/valera-4.3_r1/.repo/repo/subcmds/sync.py", line 270, in _FetchProjectList
    success = self._FetchHelper(opt, project, *args, **kwargs)
  File "/home/ase/valera/valera-4.3_r1/.repo/repo/subcmds/sync.py", line 314, in _FetchHelper
    prune=opt.prune)
  File "/home/ase/valera/valera-4.3_r1/.repo/repo/project.py", line 1229, in Sync_NetworkHalf
    self._InitGitDir(force_sync=force_sync)
  File "/home/ase/valera/valera-4.3_r1/.repo/repo/project.py", line 2267, in _InitGitDir
    raise e
GitError: --force-sync not enabled; cannot overwrite a local work tree. If you're comfortable with the possibility of losing the work tree's git metadata, use `repo sync --force-sync dalvik` to proceed.

**Comment by frankhuhu** [comment]
Looks like it's a problem from repo. Did you use the most recent repo script? Try the command mentioned "repo sync --force-sync dalvik". Also, the AOSP version is 4.3_r1 Jelly Bean.
